//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
            this.RosterOrders = new HashSet<RosterOrder>();
        }
    
        public int OrderID { get; set; }
        public int RetailerID { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Status { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<RosterOrder> RosterOrders { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
