//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public Roster()
        {
            this.RosterOrders = new HashSet<RosterOrder>();
        }
    
        public int RosterID { get; set; }
        public int UserID { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<RosterOrder> RosterOrders { get; set; }
    }
}
